### ISSUE TITLE
Add configuration option to strip the part after `+` in the e-mail addr.

### ISSUE THREAD

**Issue by Vratislav** [Applifting/parse_name_from_email#2]

**Comment by sshaw** [comment]
I agree.  Really `config.friendly_plus_part = false` should do this. 

Is there really a use case to turn `example+something123@gmail.com` into `Example Something 123`?
Anything after `+` cannot be considered part of the name because it's not part of the email.

**Comment by prokopsimek** [comment]
@sshaw Do you think that it should be stripped each time (without configuration) or as default configuration should be set to strip the plus part and you can set it to true, if you'll want it?

**Comment by sshaw** [comment]
> Do you think that it should be stripped each time (without configuration)

No. For the sake a backwards compatibility I would not do this. Keep `config.friendly_plus_part` defaulting to `false`. If it's true, then strip everything after `+`. 

For example:

```
irb [2.3.0] (ruby)$ ParseNameFromEmail.parse_name_from('skye.shaw+foo@a.com')
=> "Skye Shaw (foo)"
irb [2.3.0] (ruby)$ ParseNameFromEmail.configure { |c| c.friendly_plus_part = false }
=> false
irb [2.3.0] (ruby)$ ParseNameFromEmail.parse_name_from('skye.shaw+foo@a.com')
=> "Skye Shaw"
```

**Comment by prokopsimek** [comment]
done with PR #9
