### ISSUE TITLE
Better Name Detection Algorithm?

### ISSUE THREAD

**Issue by sshaw** [Applifting/parse_name_from_email#7]
Checkout [this library](https://github.com/frejnorling/EmailName). 

It can handle something like `mårten12_.sÖderBerg12@example.com`, which currently results in:

```
irb [2.1.5] (test_cg)$ ParseNameFromEmail.parse_name_from('mårten12_.sÖderBerg12@example.com')
=> "Mårten 12 SÖder Berg 12"
```

**Comment by prokopsimek** [comment]
@sshaw Thanks for tip! I'll improve it!

**Comment by sshaw** [comment]
You guys going to do a 0.2.0 release with these changes?

**Comment by prokopsimek** [comment]
@sshaw What's wrong? It's not a bug, it's a feature. :)

**Comment by sshaw** [comment]
> @sshaw What's wrong? It's not a bug, it's a feature. :)

Yes, it's not a bug. 

I was asking if you could push 0.2.0 to RubyGems. Currently [only 0.1.1 is available](https://rubygems.org/gems/parse_name_from_email).

**Comment by prokopsimek** [comment]
@sshaw oh, ofc... :) I'm going to do it right now.
